# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDnqBx52p8zciwzUS_1nXWHjV2MiP8j
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
filename = 'modelo-class.pkl'
modelo, min_max_scaler, variables, _ = pickle.load(open(filename, 'rb'))

# --- 1. CONFIGURACIÓN Y UI MEJORADA (COLORES) ---
st.set_page_config(page_title="Predicción Cardíaca", page_icon="🫀", layout="centered")

st.markdown("""
    <div style='background-color: #1D3557; padding: 15px; border-radius: 10px; margin-bottom: 20px;'>
        <h1 style='text-align: center; color: #F1FAEE; margin: 0;'>🩺 Evaluador de Riesgo Cardíaco</h1>
        <p style='text-align: center; color: #A8DADC; margin: 0;'>Sistema de predicción basado en Machine Learning</p>
    </div>
""", unsafe_allow_html=True)

# --- 2. CARGA DEL MODELO ---
# Se asume que el modelo guardado retorna 3 elementos al igual que en tu ejemplo
try:
    filename = 'modelo.pkl' # Asegúrate de que este sea el nombre real de tu archivo
    modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))
except Exception as e:
    st.error("Por favor, asegúrate de colocar tu archivo .pkl en la misma carpeta.")

# --- 3. INTERFAZ GRÁFICA PARA CAPTURA DE DATOS ---
st.markdown("<h4 style='color: #457B9D;'>Ingresa los datos del paciente:</h4>", unsafe_allow_html=True)

# Usamos columnas para darle un orden más limpio y espaciado a los colores
col1, col2 = st.columns(2)

with col1:
    age = st.slider('Edad[cite: 1]', min_value=1, max_value=100, value=40, step=1)
    ever_married = st.selectbox('¿Alguna vez casado?[cite: 1]', ['Yes', 'No'])
    smoking_status = st.selectbox('Estado de tabaquismo[cite: 1]', ["'never smoked'", "smokes", "formerly smoked", "Unknown"])

with col2:
    avg_glucose_level = st.number_input('Nivel medio de glucosa[cite: 1]', min_value=0.0, max_value=350.0, value=100.0)
    hypertension = st.selectbox('¿Padece hipertensión?[cite: 1]', ['Yes', 'No'])
    heart_disease = st.selectbox('¿Enfermedad del corazón previa?[cite: 1]', ['Yes', 'No'])

# Dataframe con la captura de datos
datos = [[age, hypertension, heart_disease, ever_married, avg_glucose_level, smoking_status]]
data = pd.DataFrame(datos, columns=['age', 'hypertension', 'heart_disease', 'ever_married', 'avg_glucose_level', 'smoking_status'])

st.markdown("<hr>", unsafe_allow_html=True)

# --- 4. 1 BOTÓN DE PREDICCIÓN ---
if st.button('🧠 Ejecutar Predicción', use_container_width=True):

    # Preparación de los datos futuros tal como en tu código original
    data_preparada = data.copy()

    # En despliegue drop_first= False
    data_preparada = pd.get_dummies(data_preparada, columns=['hypertension', 'heart_disease', 'ever_married', 'smoking_status'], drop_first=False, dtype=int)

    # Se adicionan las columnas faltantes (igualación con las variables del entrenamiento)
    data_preparada = data_preparada.reindex(columns=variables, fill_value=0)

    # Se normalizan los datos numéricos (como Edad y Nivel de Glucosa)
    # En los despliegues no se llama fit, solo transform
    data_preparada[['age', 'avg_glucose_level']] = min_max_scaler.transform(data_preparada[['age', 'avg_glucose_level']])

    # Predicción
    Y_pred = modelo.predict(data_preparada)

    # --- 5. RESULTADO VISUAL MEJORADO ---
    st.markdown("<br>", unsafe_allow_html=True)
    if Y_pred[0] == 'Yes' or Y_pred[0] == 1:
        st.markdown("""
        <div style='background-color: #FAD2E1; padding: 20px; border-radius: 10px; border-left: 8px solid #E63946;'>
            <h3 style='color: #E63946; margin:0;'>⚠️ Riesgo Alto Detectado</h3>
            <p style='color: #9D0208; margin:0;'>El modelo predice una alta probabilidad de ataque al corazón.</p>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown("""
        <div style='background-color: #D8F3DC; padding: 20px; border-radius: 10px; border-left: 8px solid #2D6A4F;'>
            <h3 style='color: #2D6A4F; margin:0;'>✅ Riesgo Bajo Detectado</h3>
            <p style='color: #1B4332; margin:0;'>El modelo predice una baja probabilidad de ataque al corazón.</p>
        </div>
        """, unsafe_allow_html=True)